### ISSUE TITLE
Fails to build with Frama-C 18.0

### ISSUE THREAD

**Issue by jimon** [AllanBlanchard/Frama-C-Conc2Seq#1]
When I'm trying to run `autoconf`, `./configure`, `make`, I'm getting the following result:

```
File "specified_atomic.ml", line 44, characters 21-35:
Error: This expression has type Cil_types.acsl_extension list
       but an expression was expected of type
         (string * Cil_types.acsl_extension_kind) list
       Type
         Cil_types.acsl_extension =
           int * string * Cil_types.location * Cil_types.acsl_extension_kind
       is not compatible with type string * Cil_types.acsl_extension_kind
```

After skipping it with `make -i` it seems like this is the only error in the source code.

**Comment by AllanBlanchard** [comment]
Thank you for reporting the issue. I will fix this (and also the compatibility with 19).

**Comment by AllanBlanchard** [comment]
Note: the compatibility with 19 will be directly added to the master, so use the 18-Ar branch if you want to keep Frama-C 18.
